# Site settings
title: Terminal
name: Benjamin 
email:
description: >
    Code for Fun. 
baseurl: ""
url: "https://itisbenjamin.github.io" 
twitter_username: 
github_username: 
disqus_username: 

google-analytics: UA-75034651-1 # add it if you have one

# Build settings
permalink: none
markdown: kramdown
